name: StorybookCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the stack
        run: npm install
      - name: Percy Test
        uses: percy/exec-action@v0.3.0
        with:
          command: "npm run snapshot"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}        